'use client';

import { usePathname } from "next/navigation";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const pathname = usePathname();
    console.log(pathname);
    
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
